language: node_js
node_js:
  - "9"

dist: trusty

sudo: false

branches:
  only:
  - master

env:
  global:
    secure: "Vm8weRLBqaSTDEpD14RqC9PUrUp0hyC2vKwEw/m9PGy4ORs2wwm0K4qXTIJjgTxsurYRe6gPc0zAtSj5WxvvXihrOXbY9ZtEG1J+WyL3W6fMSmvJMtq0XmxBN5qET64CAtU9yH1QCA6wkyf7eRDF3Od5eO2NymGqE9YxsKqHKO0GtqgM6U12PzURPDtVTnZLfj/H24Bt1XjyECm6R8JQlQbCwQjYOskW91jxha3x3tqygC42WX78/SQU5ck8/9cjWrJP6JLfQ3OfLfHdS2rcmP6fyZetfKwtaMzf5+1pUzQD/YA+KHZjWL8K/a+2bJ3N7GhWQ5ErGWb0kSpbGlNi+arz5ijSFNN7lOSGCFrCOsRslHhlRmmSxmXO4o4W+PfXNUA9oDpWtwHqk9FJkhRw2fPYpfAXFeowefPOsTAjXeGrZPxQ64AgNx1utVlfSY9z4h7+gjLuS73TFmVH1AYje2CVOsSumPWvaw6Z1n/9M5eiYqKTsT7ENfhgI7c2xEAAvnbrDa5qpa84wRP5I/q0zUA6RLpKwzWUxLyUyveR2CIfpC4bQvl/uHpkrhQihpYqxknjg24+EnuQ5C9VqH83r5PpxaSevm+SswLqyBJF9oCHQPYu13whGueUDMGWP/clroK25S31j3NTeAGTQezVzD/CQyLfx/2ZKJmzr7gJ2hY="

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - npm i

script:
  - npm run lint
  - npm run build
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
